apiVersion: v1
kind: Namespace
metadata:
  name: tream-landing-page
  labels:
    git-engine: gitlab
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tream-landing-page
  namespace: ops-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: tream-landing-page
spec:
  project: default
  source:
    repoURL: https://git.adorsys.de/mobile-quest/landing-page.git
    targetRevision: kaaas-migration
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: tream-landing-page
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
