apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-gitlab
  namespace: ops-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: helloworld-gitlab
spec:
  project: default
  source:
    repoURL: https://git.adorsys.de/adorsys/devops/ops-k8s-bootstrap.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: helloworld-gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
---