apiVersion: v1
kind: Namespace
metadata:
  name: listmonk
  labels:
    git-engine: gitlab
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: listmonk
  namespace: ops-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: listmonk
spec:
  project: default
  source:
    repoURL: https://https://git.adorsys.de/adorsys/listmonk.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: listmonk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
