apiVersion: v1
kind: Namespace
metadata:
  name: sopra-maven-proxy
  labels:
    git-engine: gitlab
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sopra-maven-proxy
  namespace: ops-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: sopra-maven-proxy
spec:
  project: default
  source:
    repoURL: https://git.adorsys.de/sdv/sdv-connector.git
    targetRevision: mvnproxy_migration_to_akp
    path: infra/mavenProxy/kubernetes
    helm:
      releaseName: mavenproxy
  destination:
    server: https://kubernetes.default.svc
    namespace: sopra-maven-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
