apiVersion: v1
kind: Namespace
metadata:
  name: adorsys-tech-radar
  labels:
    git-engine: gitlab
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adorsys-tech-radar
  namespace: ops-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: adorsys-tech-radar
spec:
  project: default
  source:
    repoURL: https://git.adorsys.de/technology-world/adorsys-tech-radar.git
    targetRevision: migrate2kaaas
    path: adorsys-tech-radar
    helm:
      releaseName: showroom
  destination:
    server: https://kubernetes.default.svc
    namespace: adorsys-tech-radar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
