apiVersion: v1
kind: Namespace
metadata:
  name: user-pw-change
  labels:
    git-engine: gitlab
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-pw-change
  namespace: ops-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: user-pw-change
spec:
  project: default
  source:
    repoURL: https://git.adorsys.de/admins/dockerfiles.git
    targetRevision: master
    path: user-password-change/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: user-pw-change
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
