on:
  push:
    branches:
      - main

jobs:
  getDirs:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v3
      - id: set-dirs
        run: echo "dir=$(ls -d *-cluster/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  apply:
    runs-on: ubuntu-latest
    needs: [getDirs]
    strategy:
      matrix:
        cluster: ${{fromJson(needs.getDirs.outputs.dir)}}
    defaults:
      run:
        working-directory: ${{ matrix.cluster }}
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    - name: Terraform Init
      id: init
      run: terraform init -upgrade
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Setup Kubeconfig
      id: kubeconfig
      run: |
        curl -X GET "https://kaas.cloudpunks.io/api/v2/projects/j26n8v9zmw/clusters/xm6ff2rfvq/kubeconfig" \
        -H  "accept: application/octet-stream" -H "Authorization: Bearer ${{ secrets.SA_SERVICE_CLUSTER }}" > .kubeconfig
        chmod go-r .kubeconfig
        export KUBECONFIG=.kubeconfig

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
